# Generated by Django 4.2.3 on 2023-07-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('tmdb_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('release_year', models.IntegerField()),
                ('image', models.FilePathField(path='/img')),
            ],
        ),
    ]
