# Generated by Django 4.2.3 on 2023-07-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.CharField(max_length=1000),
        ),
    ]
