# Generated by Django 4.2.3 on 2023-07-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_feed', '0003_alter_movie_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='image',
        ),
        migrations.AddField(
            model_name='movie',
            name='background_path',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_path',
            field=models.URLField(default=''),
        ),
    ]
