# Generated by Django 4.2.3 on 2023-07-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_feed', '0004_remove_movie_image_movie_background_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='', max_length=100),
        ),
    ]
